name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Backend/Backend
      run: dotnet restore
    - name: Build
      working-directory: ./Backend/Backend
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Backend/Backend
      run: dotnet test /p:CollectCoverage=true --no-build --verbosity normal
